[theme]
primaryColor = "#a67129"
backgroundColor = "#1E1611"
secondaryBackgroundColor = "#2D2419"
textColor = "#a67a29"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
