[theme]
primaryColor = "#f0e0cc"
backgroundColor = "#1E1611"
secondaryBackgroundColor = "#2D2419"
textColor = "#f0e0cc"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
