[theme]
primaryColor = "#e3c296"
backgroundColor = "#1E1611"
secondaryBackgroundColor = "#2D2419"
textColor = "#d4c3a5"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
