[theme]
primaryColor = "#D2B48C"
backgroundColor = "#1E1611"
secondaryBackgroundColor = "#2D2419"
textColor = "#F5DEB3"

[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
